# Generated by Django 2.2.4 on 2019-08-22 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('completed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 8, 22, 3, 0, 10, 892376, tzinfo=utc))),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
