# Generated by Django 2.2.4 on 2019-09-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salvageLogForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='LumberyardInquiryCheck',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='MillingKilnInquiryCheck',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='SalvageLogInquiryCheck',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
