# Generated by Django 2.2.4 on 2019-09-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salvageLogForm', '0002_auto_20190924_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='LumberyardInquiryCheck',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='MillingKilnInquiryCheck',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='SalvageLogInquiryCheck',
            field=models.BooleanField(default='False'),
        ),
    ]
