# Generated by Django 2.2.4 on 2019-09-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salvageLogForm', '0002_auto_20190924_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='LumberyardInquiryCheck',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='MillingKilnInquiryCheck',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='SalvageLogInquiryCheck',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
