# Generated by Django 2.2.4 on 2019-09-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salvageLogForm', '0003_auto_20190924_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='LumberyardInquiryCheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='MillingKilnInquiryCheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='SalvageLogInquiryCheck',
            field=models.BooleanField(default=False),
        ),
    ]
