# Generated by Django 2.2.4 on 2019-09-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salvageLogForm', '0003_auto_20190925_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalvageLogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_species', models.CharField(max_length=100)),
                ('trunk_diameter', models.IntegerField()),
                ('trunk_crotch_height', models.IntegerField()),
                ('address_ln1', models.CharField(max_length=100)),
                ('address_ln2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
            ],
        ),
    ]
