# Generated by Django 2.2.4 on 2019-09-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salvageLogForm', '0004_auto_20190924_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='LumberyardInquiryCheck',
            new_name='lumberyardInquiryCheck',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='MillingKilnInquiryCheck',
            new_name='millingKilnInquiryCheck',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='SalvageLogInquiryCheck',
            new_name='salvageLogInquiryCheck',
        ),
    ]
