# Generated by Django 2.2.4 on 2019-09-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salvageLogForm', '0005_auto_20190924_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='lumberyardInquiryCheck',
            new_name='LumberyardInquiryCheck',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='millingKilnInquiryCheck',
            new_name='MillingKilnInquiryCheck',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='salvageLogInquiryCheck',
            new_name='SalvageLogInquiryCheck',
        ),
    ]
